=== marthacoding/marthacoding.github.io/project4/Cruises.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://github.com/marthacoding/marthacoding.github.io/blob/main/project4/Cruises.xml"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Cruises">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="Cruise">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ParentCompany" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="Reservation" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Phone" type="xs:string" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Url" type="xs:string" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Headquarters">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="City" type="xs:string" minOccurs="1" maxOccurs="1" />
										<xs:element name="State" type="xs:string" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="Zip" type="xs:unsignedInt" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="DeparturePorts">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Port" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="FoundedIn" type="xs:unsignedShort" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== marthacoding/marthacoding.github.io/project4/CruisesModified.xml
<Cruises
	xmlns="https://marthacoding.github.io/project4/Cruises.xml" xsi:schemaLocation="https://marthacoding.github.io/project4/Cruises.xsd
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	<Cruise FoundedIn="1972">
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Cruise Line</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarters Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Baltimore</Port>
			<Port>Los Angeles</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>American Cruise Lines</ParentCompany>
		<Name>American Cruise Lines</Name>
		<Reservation>
			<Phone>800-460-4518</Phone>
			<Url>www.americancruiselines.com</Url>
		</Reservation>
		<Headquarters Zip="06437">
			<City>Guilford</City>
			<State>Connecticut</State>
		</Headquarters>
		<DeparturePorts>
			<Port>New England</Port>
			<Port>San Francisco</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Celebrity Cruises</ParentCompany>
		<Name>Celebrity Cruise Line</Name>
		<Reservation>
			<Phone>1-888-751-7804</Phone>
			<Url>www.celebritycruises.com</Url>
		</Reservation>
		<Headquarters Zip="33132">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Fort Lauderdale</Port>
			<Port>Tampa</Port>
			<Port>San Diego</Port>
			<Port>Los Angeles</Port>
			<Port>Cozumel</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise FoundedIn="1995">
		<ParentCompany>The Walt Disney Company </ParentCompany>
		<Name>Disney Cruise Line</Name>
		<Reservation>
			<Phone>1-888-751-7804</Phone>
			<Url>www.disneycruise.disney.go.com</Url>
		</Reservation>
		<Headquarters Zip="34747">
			<City>Celebration</City>
			<State>Florida</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Auckland, New Zealand</Port>
			<Port>Barcelona, Spain</Port>
			<Port>Brisbane, Australia</Port>
			<Port>Civitavecchia, Italy</Port>
			<Port>Miami, Florida</Port>
			<Port>New Orleans, Louisiana</Port>
			<Port>Honolulu, Hawaii</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Emerald Cruises </ParentCompany>
		<Name>Splendours of Europe</Name>
		<Reservation>
			<Phone>1-857-201-2212</Phone>
			<Url>www.emeraldcruises.com</Url>
		</Reservation>
		<Headquarters Zip="02135">
			<City>Boston</City>
			<State>Massachussets</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Amsterdam</Port>
			<Port>Budapest</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise  FoundedIn="2014">
		<ParentCompany>Pearl Seas Cruises</ParentCompany>
		<Name>Canadian Maritimes</Name>
		<Reservation>
			<Phone>1-800-981-9146</Phone>
			<Url>www.pearlseascruises.com</Url>
		</Reservation>
		<Headquarters Zip="06437">
			<City>Guilford</City>
			<State>Connecticut</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Portland</Port>
			<Port>Bar Harbor</Port>
			<Port>Halifax</Port>
			<Port>Pictou</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Scenic Luxury Cruises Tours</ParentCompany>
		<Name>France River Cruises</Name>
		<Reservation>
			<Phone>1-857-201-3407</Phone>
			<Url>www.scenicusa.com</Url>
		</Reservation>
		<Headquarters Zip="02135">
			<City>Boston</City>
			<State>Massachussets</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Gironde</Port>
			<Port>Dordogne</Port>
			<Port>Garonne</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise FoundedIn="2017" >
		<ParentCompany>Princess Cruises</ParentCompany>
		<Name>Majestic Princess</Name>
		<Reservation>
			<Phone>1-800-774-6237</Phone>
			<Url>www.princess.com</Url>
		</Reservation>
		<Headquarters Zip="91355">
			<City>Santa Clarita</City>
			<State>California</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Los Angeles, California</Port>
			<Port>Fort Laurderle, Florida</Port>
			<Port>Galveston Texas</Port>
			<Port>New York City, New York</Port>
			<Port>Melbourne Australia</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise >
		<ParentCompany>Windstar Cruises</ParentCompany>
		<Name>Teasures of the Greek Isles</Name>
		<Reservation>
			<Phone>855-898-8656</Phone>
			<Url>www.windstarcruises.com</Url>
		</Reservation>
		<Headquarters Zip="98121">
			<City>Seattle</City>
			<State>Washington</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Athens</Port>
			<Port>Kusadasi</Port>
			<Port>Nafplio</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise  >
		<ParentCompany>Oceania Cruises</ParentCompany>
		<Name>Oceania Cruise Line</Name>
		<Reservation>
			<Phone>1-855-623-2642</Phone>
			<Url>www.oceaniacruises.com</Url>
		</Reservation>
		<Headquarters Zip="33126">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarters>
		<DeparturePorts>
			<Port>Cabo San Lucas, Mexico</Port>
			<Port>Catalina Island, California</Port>
			<Port>Doha, Qatar</Port>
			<Port>Dubai, UAE</Port>
		</DeparturePorts>
	</Cruise>
</Cruises>
